[color]
  bg = "black" # none for transparent
  fg = "white"
  important = 'magenta'
  error = 'red'
  warning = 'yellow'
  info = 'cyan'
[color.type]
  folder = 'blue'
  executable = 'green'
  archives = 'red'
  images = 'magenta'
  audio = 'cyan'
  video = 'magenta'
  mappings = [
    {name = '.md', color = 'cyan'}
  ]
[layout]
  leftPanel = 0.2
  rightPanel = 0.5
  cursor = 'center' # top, top-padded, center
[preview]
  text = 'cat'
  image = 'chafa'
  audio = 'ffplay'
  video = 'ffplay'

mappings = [
  {name = 'images', files = [".png", ".jpg", ".jpeg", ".gif", ".svg", ".tiff"]},
]
